### ISSUE TITLE
Подскажите плиз по OpenOCD

### ISSUE THREAD

**Issue by ogneyar** [Fabmicro-LLC/MIK32_Blink#1]
Я под win10 пытаюсь прошить АМУР на плате ELBEAR ACE-UNO, на строке openocd.run(f"adapter speed {adapter_speed}") выскакивает исключение. Может OpenOCD у меня не тот? Я использую xpack-openocd-0.10.0-15. Какой используете вы?

**Comment by pointcheck** [comment]
Я прошивал из под FreeBSD и из под Linux, проблем не было. Вот вывод верисии на FreeBSD:

```
rz@butterfly:~ % openocd -v
Open On-Chip Debugger 0.12.0
```

Пришлите полный вывод вместе с командой и её параметрами. Попытаюсь помочь.

**Comment by ogneyar** [comment]
Вот если uploader'у указать путь до openOCD:

python E:/GitFlic/C_study/MIK_c/AMUR/libs/mik32-uploader/mik32_upload.py --run-openocd --openocd-exec=`openocd` --openocd-scripts E:/GitFlic/C_study/MIK_c/AMUR/libs/mik32-uploader/openocd-scripts --openocd-interface interface/ftdi/mikron-link.cfg C:/Users/User/Desktop/AMUR/nBlink/build/firmware.hex

Using MIK32V2
Start Linear Address:  0x1000000
Traceback (most recent call last):
  File "E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\mik32_upload.py", line 228, in upload_file
    proc = run_openocd(openocd_exec, openocd_scripts,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\mik32_upload.py", line 141, in run_openocd
    proc = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Не удается найти указанный файл

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\mik32_upload.py", line 429, in <module>
    upload_file(
  File "E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\mik32_upload.py", line 234, in upload_file
    raise OpenOCDStartupException(e)
OpenOCDStartupException: [WinError 2] Не удается найти указанный файл
make: *** [flash] Ошибка 1

**Comment by ogneyar** [comment]
А если без --run-openocd:

python E:/GitFlic/C_study/MIK_c/AMUR/libs/mik32-uploader/mik32_upload.py C:/Users/User/Desktop/AMUR/nBlink/build/firmware.hex

Using MIK32V2
Start Linear Address:  0x1000000
Traceback (most recent call last):
  File "E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\mik32_upload.py", line 429, in <module>
    upload_file(
  File "E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\mik32_upload.py", line 239, in upload_file
    openocd.run(f"adapter speed {adapter_speed}")
  File "E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\tclrpc.py", line 106, in run
    reply = self.sendrecv(wrap)
            ^^^^^^^^^^^^^^^^^^^
  File "E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\tclrpc.py", line 74, in sendrecv
    self.sock.sendall(data)
OSError: [WinError 10057] Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied
make: *** [flash] Ошибка 1

**Comment by ogneyar** [comment]
Я склоняюсь к тому что с JTAG'ом что то не то. Установил MikronIDE, при попытки дебага OpenOCD ругается на отсутствие подключения

Open On-Chip Debugger 0.12.0+dev-syntacore-2023-11-release-gf0391689 (2023-11-28-07:27)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : set servers polling period to 200ms
Info : clock speed 4000 kHz
Error: JTAG scan chain interrogation failed: all ones
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Error: riscv.cpu: IR capture error; saw 0x1f not 0x01
Warn : Bypassing JTAG setup events due to errors
Error: [riscv.cpu] Unsupported DTM version: 15
Warn : target riscv.cpu examination failed
Info : starting gdb server for riscv.cpu on 3333
Info : Listening on port 3333 for gdb connections
Error: Target not examined yet

Error: [riscv.cpu] Unsupported DTM version: -1
Error: [riscv.cpu] Could not identify target type.

**Comment by pointcheck** [comment]
Пути указываемые в параметрах у питонового скрипта ```mik32_upload.py``` должны быть заданы относительно каталога его размещения, то есть относительно ```E:\GitFlic\C_study\MIK_c\AMUR\libs\mik32-uploader\```. Укажите их так, как они присутствуют в Makefile-е в этом репозитории.  Я надеюсь винда понимает прямые слэши в путях ? :)

В ```--openocd-exec=``` путь надо указать полностью вместе с именем исполняемого файла ```openocd.exe```.

**Comment by ogneyar** [comment]
Поставил перемычку boot0, я так понимаю загрузился с оперативки?

openocd -f ../libs/Util/m-link.cfg -f ../libs/Util/mik32.cfg

OpenOCD запустился, но всё таки с ошибкой:

init done
Open On-Chip Debugger 0.12.0+dev-syntacore-2023-08-release-g45609341 (2023-08-10-00:05)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : set servers polling period to 10ms
Info : usb device reset successful
Info : clock speed 4000 kHz
Info : JTAG tap: riscv.cpu tap/device found: 0xdeb11001 (mfg: 0x000 (<invalid>), part: 0xeb11, ver: 0xd)
Info : TAP riscv.sys does not have valid IDCODE (idcode=0xfffffffe)
Info : [riscv.cpu] datacount=2 progbufsize=6
Info : [riscv.cpu] Examined RISC-V core; found 1 harts
Info : [riscv.cpu]  XLEN=32, misa=0x40001104
[riscv.cpu] Target successfully examined.
Info : starting gdb server for riscv.cpu on 3333
Info : Listening on port 3333 for gdb connections
Started by GNU MCU Eclipse
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : accepting 'gdb' connection on tcp/3333
undefined debug reason 8 - target needs reset
Warn : Prefer GDB command "target extended-remote :3333" instead of "target remote :3333"
Error: JTAG scan chain interrogation failed: all ones
Error: Check JTAG interface, timings, target power, etc.
Error: Trying to use configured scan chain anyway...
Warn : Bypassing JTAG setup events due to errors
Disabling watchdog...
Info : JTAG tap: riscv.cpu tap/device found: 0xdeb11001 (mfg: 0x000 (<invalid>), part: 0xeb11, ver: 0xd)
Info : TAP riscv.sys does not have valid IDCODE (idcode=0xfffffffe)

**Comment by pointcheck** [comment]
Вывод openocd нормальный, ядро RISC-V обаружено. IDCODE у него нестандартный. Пробуйте прошивать.

Я прошивал в EEPROM и запускал от туда же - обе перемычки сняты.

**Comment by ogneyar** [comment]
Прошил с установленной перемычкой при помощи [SyntacoreIDE](https://forum.mik32.ru/index.php?threads/ide-для-mik32-Амур-на-основе-syntacore-ide.93/), ещё не до конца разобрался в чём причина, но MikronIDE не позволяет прошить.

А через консоль прошил только отдельно запустив OpenOCD командой openocd -f ../libs/Util/m-link.cfg -f ../libs/Util/mik32.cfg и в отдельной консоли запустил Uploader командой mik32_upload.exe build/freertos.hex.

freertos.hex скомпилирован SyntacoreIDE, ищу проблему в том как я компилирую ...

Главное я выяснил что ELJTAG рабочий, МК рабочий. Пока остаётся загадкой почему не хочет прошиваться во флеш

**Comment by ogneyar** [comment]
Прошивку и свою залил, получилось

**Comment by ogneyar** [comment]
Uploader  заработал когда я прошивку первой указал, а потом уже флаги:

C:\sc-dt\tools\mik32-uploader-master\dist\mik32_upload.exe build/firmware.hex --run-openocd --openocd-exec="C:\sc-dt\tools\bin\openocd.exe" --openocd-interface="C:\sc-dt\workspace\MIK32_SRC\scripts\m-link.cfg" --openocd-target="C:\sc-dt\workspace\MIK32_SRC\scripts\mik32.cfg" --adapter-speed=4000

Записываю во флеш, но всё ещё с перемычкой на boot0

**Comment by ogneyar** [comment]
Всё, решил проблему, благодарю.

Записал с перемычкой на boot0 во флеш программу, а после этого прошивается и без перемычки. Видимо какая-то залитая программа во флеш мешала программировать.

Ну и квест я прошёл)) Фуух...

**Comment by pointcheck** [comment]
Поздравляю! :)

**Comment by ogneyar** [comment]
Благодарю!

**Comment by pointcheck** [comment]
Проблема решена подгонкой путей к скриптам.
